/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Taskaler */

#ifndef _Included_Taskaler
#define _Included_Taskaler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Taskaler
 * Method:    getTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Taskaler_getTest
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
