/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class taskaler_ui_hook_DLLConnector */

#ifndef _Included_taskaler_ui_hook_DLLConnector
#define _Included_taskaler_ui_hook_DLLConnector
#ifdef __cplusplus
extern "C" {
#endif
#undef taskaler_ui_hook_DLLConnector_WM_HOTKEY
#define taskaler_ui_hook_DLLConnector_WM_HOTKEY 66L
#undef taskaler_ui_hook_DLLConnector_MOD_ALT
#define taskaler_ui_hook_DLLConnector_MOD_ALT 1L
/*
 * Class:     taskaler_ui_hook_DLLConnector
 * Method:    isHotKeyPressed
 * Signature: (IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_taskaler_ui_hook_DLLConnector_isHotKeyPressed
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
